const mongoose = require('mongoose');

const schema = new mongoose.Schema({
  pageSlug:       { type: String, required: true },
  blockKey:       { type: String, required: true },
  label:          { type: String, required: true },
  blockType:      { type: String, enum: ['text', 'textarea', 'image'], default: 'text' },
  content:        { type: String, default: '' },
  image:          { type: String, default: '' },
  htmlTag:        { type: String, default: null },
  fontFamily:     { type: String, default: null },
  fontSize:       { type: String, default: null },
  fontWeight:     { type: String, default: null },
  fontStyle:      { type: String, default: null },
  textDecoration: { type: String, default: null },
  textColor:      { type: String, default: null },
  lineHeight:     { type: String, default: null },
  letterSpacing:  { type: String, default: null },
  textAlign:      { type: String, default: null },
  marginTop:      { type: String, default: null },
  marginRight:    { type: String, default: null },
  marginBottom:   { type: String, default: null },
  marginLeft:     { type: String, default: null },
  paddingTop:     { type: String, default: null },
  paddingRight:   { type: String, default: null },
  paddingBottom:  { type: String, default: null },
  paddingLeft:    { type: String, default: null },
  width:          { type: String, default: null },
  height:         { type: String, default: null },
  minHeight:      { type: String, default: null },
  maxWidth:       { type: String, default: null },
  maxHeight:      { type: String, default: null },
  // Arabic content & styles
  contentAr:        { type: String, default: '' },
  fontFamilyAr:     { type: String, default: null },
  fontSizeAr:       { type: String, default: null },
  fontWeightAr:     { type: String, default: null },
  fontStyleAr:      { type: String, default: null },
  textDecorationAr: { type: String, default: null },
  textColorAr:      { type: String, default: null },
  lineHeightAr:     { type: String, default: null },
  letterSpacingAr:  { type: String, default: null },
  textAlignAr:      { type: String, default: null },
  marginTopAr:      { type: String, default: null },
  marginRightAr:    { type: String, default: null },
  marginBottomAr:   { type: String, default: null },
  marginLeftAr:     { type: String, default: null },
  paddingTopAr:     { type: String, default: null },
  paddingRightAr:   { type: String, default: null },
  paddingBottomAr:  { type: String, default: null },
  paddingLeftAr:    { type: String, default: null },
  widthAr:          { type: String, default: null },
  heightAr:         { type: String, default: null },
  minHeightAr:      { type: String, default: null },
  maxWidthAr:       { type: String, default: null },
  maxHeightAr:      { type: String, default: null },
});

schema.index({ pageSlug: 1, blockKey: 1 }, { unique: true });

module.exports = mongoose.model('PageContentBlock', schema);
